name: echomeet

description: A new Flutter project.
publish_to: 'none' # Ensures package is not accidentally published to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  printing: ^5.11.1
  provider: ^6.0.5
  uuid: ^4.2.1
  shared_preferences: ^2.0.17
  firebase_storage: ^13.4.6
  cloud_firestore: ^6.8.0
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  flutter_local_notifications: ^22.3.0
  timeago: ^3.6.0
  adaptive_theme: ^3.4.1
  image_picker: ^1.0.4
  pdf: ^3.10.7
  password_strength: ^0.2.0
  url_launcher: ^6.2.5
  firebase_messaging: ^16.5.0
  carousel_slider: ^5.1.2
  local_auth: ^3.0.2
  local_auth_android: ^2.0.9
  flutter_quill: ^11.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
