name: survey_app_ks
description: A new Flutter project.
publish_to: 'none' # Ensures package is not accidentally published to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  printing: ^5.11.1
  provider: ^6.0.5
  uuid: ^4.2.1
  shared_preferences: ^2.0.17
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.8.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  flutter_local_notifications: ^16.2.0
  timeago: ^3.6.0
  adaptive_theme: ^3.4.1
  image_picker: ^1.0.4
  country_code_picker: ^3.0.0
  persistent_bottom_nav_bar: ^5.0.2
  pdf: ^3.10.7
  password_strength: ^0.2.0
  url_launcher: ^6.2.5
  responsive_sizer: ^3.3.0+1
  permission_handler: ^11.3.0
  firebase_messaging: ^14.7.19
  http: ^0.13.3
  carousel_slider: ^4.1.1
  local_auth: ^2.1.8
  local_auth_android: ^1.0.37
  # flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
