// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD46ZAK41DkdZ8AKv9L4G_ARdR0V5TJ-3A',
    appId: '1:1005316799898:android:e98a6ecceb2008aac98e23',
    messagingSenderId: '1005316799898',
    projectId: 'echomeet-app',
    storageBucket: 'echomeet-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIkbOYgo_qjN6g1opTLQQQz4SvT5LM0B8',
    appId: '1:1005316799898:ios:97e44d1c4fbc76e1c98e23',
    messagingSenderId: '1005316799898',
    projectId: 'echomeet-app',
    storageBucket: 'echomeet-app.firebasestorage.app',
    iosBundleId: 'com.echomeet.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHESrdF3ty1DKz7guTv1QzBnC6fZ87q6M',
    appId: '1:1005316799898:web:75aae15cc70210fcc98e23',
    messagingSenderId: '1005316799898',
    projectId: 'echomeet-app',
    authDomain: 'echomeet-app.firebaseapp.com',
    storageBucket: 'echomeet-app.firebasestorage.app',
  );
}
